### ISSUE TITLE
how does component abstraction work?

### ISSUE THREAD

**Issue by ccorcos** [cyclejs/cycle-examples#10]
What the hell is going on here? https://github.com/cyclejs/cycle-examples/blob/master/advanced-list-nest/src/app.js#L28-L32

Is there a tutorial or something that explains some of this stuff?

I think a helpful example that would help me understand how component abstraction works is a dynamic list of counters like in the Elm tutorial: https://github.com/evancz/elm-architecture-tutorial#example-3-a-dynamic-list-of-counters

**Comment by jonathancoueraud** [comment]
From my point of view the power of cyclejs is to structure with a super easy but very intuitive functional approach your rxjs code.
So to be efficient you should read, of course the cyclejs documentation, but also the rxjs one.
And as cyclejs is very simple, generally if your are confused about some cyclejs stuff you should take a look at rxjs documentation.
Maybe this link will help you : [cold vs. hot observables](http://xgrommx.github.io/rx-book/content/getting_started_with_rxjs/creating_and_querying_observable_sequences/creating_and_subscribing_to_simple_observable_sequences.html#cold-vs-hot-observables)

**Comment by ccorcos** [comment]
Ahhh. I get it now. You're creating a Subject, piping it through the TickerComponent and connecting to it on the other side. Weird.
