### ISSUE TITLE
nested-bmi example does not update BMI in IE

### ISSUE THREAD

**Issue by arlair** [cyclejs/cycle-examples#2]
I could not get the BMI examples on the following page to update by moving the sliders using Windows 8.1 IE 11 (auto updated) or Windows Surface RT IE:

http://cycle.js.org/basic-examples.html

The BMI value always stays at 24.

Chrome and Firefox work as expected.

I did not notice any console errors. I have the same issue with a local copy taken from this repository.

**Comment by arlair** [comment]
I found that if I change the following line from listening for 'click' instead of 'input' it will now work in IE.

let newValue$ = DOM.select(`.labeled-slider${name} .slider`).events('click')

**Comment by arlair** [comment]
This is a known IE bug that doesn't look like being fixed:

https://connect.microsoft.com/IE/feedback/details/794285/ie10-11-input-event-does-not-fire-on-div-with-contenteditable-set

I can confirm 'input' events fire on Windows 10 with the Edge browser.

Work arounds such as this seem to be required to IE:
http://stackoverflow.com/questions/28118849/range-slider-input-event-not-firing-in-ie-10

**Comment by arlair** [comment]
'change' works in IE, but gives different behaviour because it updates as the slider moves. Chrome and Firefox only fire 'change' on release.

**Comment by staltz** [comment]
This issue was moved to cyclejs/core#240
